terms:
  - id: Audio
    term: Audio
  - id: Dataset
    term: Dataset
  - id: Image
    term: Image
  - id: JPG
    term: JPG
  - id: MP3
    term: MP3
  - id: MP4
    term: MP4
  - id: PDF
    term: PDF
  - id: Text
    term: Text
  - id: Thumbnail
    term: Thumbnail
  - id: TIFF
    term: TIFF
  - id: Video
    term: Video