terms:
  - id: N/A
    term: N/A
  - id: English (United States)
    term: English (United States)
  - id: English
    term: English
  - id: Spanish
    term: Spanish
  - id: German
    term: German
  - id: French
    term: French
  - id: Arabic
    term: Arabic
  - id: Italian
    term: Italian
  - id: Japanese
    term: Japanese
  - id: Chinese
    term: Chinese
  - id: Turkish
    term: Turkish
  - id: Latin
    term: Latin
  - id: Other
    term: Other