terms:
  - id: Annual report
    term: Annual report
  - id: Article
    term: Article
  - id: Audio
    term: Audio
  - id: Book
    term: Book
  - id: Book Chapter or Part of Book
    term: Book Chapter or Part of Book
  - id: Catalog
    term: Catalog
  - id: Collection
    term: Collection
  - id: Correspondence
    term: Correspondence
  - id: Dataset
    term: Dataset
  - id: Dissertation
    term: Dissertation
  - id: Filmed interview
    term: Filmed interview
  - id: Finding aid
    term: Finding aid
  - id: Image
    term: Image
  - id: Image, 3-D
    term: Image, 3-D
  - id: Interview (audio)
    term: Interview (audio)
  - id: Journal
    term: Journal
  - id: Law Review
    term: Law Review
  - id: Map
    term: Map
  - id: Musical Score
    term: Musical Score
  - id: Newsletter
    term: Newsletter
  - id: Newspaper
    term: Newspaper
  - id: Notebook
    term: Notebook
  - id: Other
    term: Other
  - id: Outline or Syllabus
    term: Outline or Syllabus
  - id: Periodical
    term: Periodical
  - id: Photobook
    term: Photobook
  - id: Postcard
    term: Postcard
  - id: Presentation
    term: Presentation
  - id: Register
    term: Register
  - id: Scrapbook
    term: Scrapbook
  - id: Technical Report
    term: Technical Report
  - id: Thesis
    term: Thesis
  - id: Video
    term: Video
  - id: Yearbook
    term: Yearbook