default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  toolbar1: undo redo | styleselect | bold italic | bullist | link | table | image | code | removeformat | fullscreen 
  plugins:
    - table
    - fullscreen
    - image
    - link
    - code
    - lists
custom:
  <<: *default
